In [1]:
!git clone https://github.com/zhouqic4/MSSP607-GitHub.git

Cloning into 'MSSP607-GitHub'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 52 (delta 15), reused 4 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (52/52), 979.97 KiB | 5.10 MiB/s, done.
Resolving deltas: 100% (15/15), done.

In [3]:
%cd /content/MSSP607-GitHub

/content/MSSP607-GitHub

In [4]:
!ls
!ls data

Add_Follders.py
Assignments
data
Participation_Activity_Week1_Exercises.ipynb
Week2_participation_activity.ipynb
week3_participation.ipynb
WeeklyModules
Zhouqi_PARTICIPATION_ACTIVITY_Week_4_ipynb.ipynb
aapl.csv  amzn.csv  fb.csv  goog.csv  nflx.csv

a. We will look at stock data from Facebook, Apple, Amazon, Netflix, and Google from different files.  We will combine them into a single file and store the dataframe for further analysis.

In [5]:
import pandas as pd

b. Read each file into a dataframe

In [6]:
fb = pd.read_csv('data/fb.csv')
aapl = pd.read_csv('data/aapl.csv')
amzn = pd.read_csv('data/amzn.csv')
nflx = pd.read_csv('data/nflx.csv')
goog = pd.read_csv('data/goog.csv')

In [8]:
aapl.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

In [9]:
print('fb:', fb.shape)
print('aapl:', aapl.shape)
print('amzn:', amzn.shape)
print('nflx:', nflx.shape)
print('goog:', goog.shape)

fb: (251, 6)
aapl: (251, 6)
amzn: (251, 6)
nflx: (251, 6)
goog: (251, 6)

c. Add a column to each dataframe, called 'ticker', indicating the ticker symbol it is for (Apple's is AAPL). This symbol is how you will look up a stock.  Each file name is the ticker symbol.

In [13]:
fb['ticker'] = 'FB'
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
nflx['ticker'] = 'NFLX'
goog['ticker'] = 'GOOG'


nflx.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889   NFLX
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369   NFLX
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616   NFLX
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240   NFLX
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178   NFLX

d. Append each file together into a single dataframe.

In [14]:
faang = pd.concat([fb, aapl, amzn, nflx, goog], ignore_index=True)
faang

            date     open     high        low    close    volume ticker
0     2018-01-02   177.68   181.58   177.5500   181.42  18151903     FB
1     2018-01-03   181.88   184.78   181.3300   184.67  16886563     FB
2     2018-01-04   184.90   186.21   184.0996   184.33  13880896     FB
3     2018-01-05   185.59   186.90   184.9300   186.85  13574535     FB
4     2018-01-08   187.20   188.90   186.3300   188.28  17994726     FB
...          ...      ...      ...        ...      ...       ...    ...
1250  2018-12-24   973.90  1003.54   970.1100   976.22   1590328   GOOG
1251  2018-12-26   989.01  1040.00   983.0000  1039.46   2373270   GOOG
1252  2018-12-27  1017.15  1043.89   997.0000  1043.88   2109777   GOOG
1253  2018-12-28  1049.62  1055.56  1033.1000  1037.08   1413772   GOOG
1254  2018-12-31  1050.96  1052.70  1023.5900  1035.61   1493722   GOOG

[1255 rows x 7 columns]

In [15]:
print(faang.shape)
faang['ticker'].value_counts()

(1255, 7)

ticker
FB      251
AAPL    251
AMZN    251
NFLX    251
GOOG    251
Name: count, dtype: int64

e. Save the results in a CSV file called 'faanf.csv'.

In [16]:
faang.to_csv('data/faanf.csv', index=False)

f. Using 'fanng.csv', use type conversion to change the 'date' column into a 'datetime' and the 'volume' column into integers.  Then sort by 'date' and 'ticker.'

In [18]:
faang = pd.read_csv('data/faanf.csv')
faang.dtypes

date       object
open      float64
high      float64
low       float64
close     float64
volume      int64
ticker     object
dtype: object

In [19]:
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype(int)
faang.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

In [20]:
faang = faang.sort_values(by=['date', 'ticker'])
faang.head(10)

           date       open       high        low      close    volume ticker
251  2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
502  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0    2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
753  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX
252  2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
503  2018-01-03  1188.3000  1205.4900  1188.3000  1204.2000   3108793   AMZN
1    2018-01-03   181.8800   184.7800   181.3300   184.6700  16886563     FB
1005 2018-01-03  1064.3100  1086.2900  1063.2100  1082.4800   1430170   GOOG
754  2018-01-03   202.0500   206.2100   201.5000   205.0500   8591369   NFLX

g. Find the seven rows within the highest value for volume.

In [21]:
faang.sort_values(by='volume', ascending=False).head(7)

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

h. Use the melt() method to make the 'date' and 'ticker' key identifiers.  Melt the remaining columns so that there are not separated.

In [22]:
melted = faang.melt(id_vars=['date', 'ticker'], value_vars=['open', 'high', 'low', 'close', 'volume'])
melted.head(10)

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000
5 2018-01-03   AAPL     open   169.2521
6 2018-01-03   AMZN     open  1188.3000
7 2018-01-03     FB     open   181.8800
8 2018-01-03   GOOG     open  1064.3100
9 2018-01-03   NFLX     open   202.0500

In [24]:
print(melted.shape)
melted[(melted['ticker'] == 'AMZN') & (melted['date'] == '2018-01-02')]

(6275, 4)

           date ticker variable       value
1    2018-01-02   AMZN     open     1172.00
1256 2018-01-02   AMZN     high     1190.00
2511 2018-01-02   AMZN      low     1170.51
3766 2018-01-02   AMZN    close     1189.01
5021 2018-01-02   AMZN   volume  2694494.00